name: crypto_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.16.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  google_fonts: ^3.0.1
  bot_toast: ^4.0.2
  intl: ^0.17.0
  provider: ^6.0.3
  sqflite: ^2.0.3
  fl_chart: ^0.55.0
  firebase_core: ^1.19.2
  firebase_auth: ^3.4.2
  cloud_firestore: ^3.3.0
  http: ^0.13.4
  camera: ^0.10.0
  image_picker: ^0.8.4+11
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  image_path: 'assets/app/icon.png'
  ios: true
  remove_alpha_ios: true
  android: 'launched_icon'
  adaptive_icon_background: '#FFFFFF'
  adaptive_icon_foreground: 'assets/app/icon.png'

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
